# Generated by Django 3.2.12 on 2022-04-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0003_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='media/default.jpg', upload_to=''),
        ),
    ]
