# Generated by Django 3.2.12 on 2022-04-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_auto_20220425_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
